version: "3.2"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8585:8585"
    volumes:
      - .:/app
    command: >
      python manage.py runserver 0.0.0.0:8585
    environment:
      DB_HOST: db
      DB_NAME: budget_app
      DB_USER: finance
      DB_PASS: password
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
       - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data